delete from item_category where systemVariable <> 1;
TRUNCATE TABLE `item_category_storefront`;
TRUNCATE TABLE `item_category_storefront_detail`;
TRUNCATE TABLE `item_category_marketplace_detail`;
TRUNCATE TABLE `item_category_marketplace_attributes`;


TRUNCATE TABLE `item_marketplace_sync_detail`;
TRUNCATE TABLE `item_marketplace_link`;

truncate item;
truncate item_unit_conversion;
truncate item_image;
truncate item_in_warehouse;
truncate item_movement;
truncate item_in_detail;
truncate item_in_header;
truncate item_out_header;
truncate item_out_detail;
truncate item_adjustment_header;
truncate item_adjustment_detail;
truncate sales_order_header;
truncate sales_order_detail;
truncate sales_order_payment;
truncate purchase_order_header;
truncate purchase_order_detail;
truncate purchase_order_payment;

TRUNCATE TABLE `ap_commission_payment_header`;
TRUNCATE TABLE `ap_commission_payment_detail`;
TRUNCATE TABLE `ap_commission_payment`;
TRUNCATE TABLE `ap_commission`;
TRUNCATE TABLE `ap`;
TRUNCATE TABLE `ap_payment_header`;
TRUNCATE TABLE `ap_payment_detail`;
TRUNCATE TABLE `ap_payment`;
TRUNCATE TABLE `ap_payable_23_payment_header`;
TRUNCATE TABLE `ap_payable_23_payment_detail`;
TRUNCATE TABLE `ap_payable_23_payment`;
TRUNCATE TABLE `ap_payable_23`;
TRUNCATE TABLE `ap_employee_commission_payment_header`;
TRUNCATE TABLE `ap_employee_commission_payment_detail`;
TRUNCATE TABLE `ap_employee_commission_payment`;
TRUNCATE TABLE `ap_employee_commission`;
TRUNCATE TABLE `ap_downpayment`;
TRUNCATE TABLE `ap_cost`;
TRUNCATE TABLE `ar_employee_payment_header`;
TRUNCATE TABLE `ar_employee_payment_detail`;
TRUNCATE TABLE `ar_employee_payment`;
TRUNCATE TABLE `ar_employee`;
TRUNCATE TABLE `ar_downpayment`;
TRUNCATE TABLE `ar_cost`;
TRUNCATE TABLE `ar`;
TRUNCATE TABLE `ar_prepaid_23_payment_header`;
TRUNCATE TABLE `ar_prepaid_23_payment_detail`;
TRUNCATE TABLE `ar_prepaid_23_payment`;
TRUNCATE TABLE `ar_prepaid_23`;
TRUNCATE TABLE `ar_payment_header`;
TRUNCATE TABLE `ar_payment_detail`;
TRUNCATE TABLE `ar_payment`;
TRUNCATE TABLE `arap_netting_header`;
TRUNCATE TABLE `arap_netting_ar_detail`;
TRUNCATE TABLE `arap_netting_ap_detail`;
TRUNCATE TABLE `car_turnover`;
TRUNCATE TABLE `car_service_maintenance_header`;
TRUNCATE TABLE `car_service_maintenance_detail`;
TRUNCATE TABLE `cash_out_header`;
TRUNCATE TABLE `cash_out_detail`;
TRUNCATE TABLE `cash_movement`;
TRUNCATE TABLE `cash_in_header`;
TRUNCATE TABLE `cash_in_detail`;
TRUNCATE TABLE `cash_bank_transfer_header`;
TRUNCATE TABLE `cash_bank_transfer_detail`;
TRUNCATE TABLE `cash_bank_transaction_type`;
TRUNCATE TABLE `cash_bank_realization_status`;
TRUNCATE TABLE `cash_bank_realization_payment`;
TRUNCATE TABLE `cash_bank_realization_header`;
TRUNCATE TABLE `cash_bank_realization_detail`;
TRUNCATE TABLE `cash_bank`;
update chart_of_account set amount = 0;
delete from chart_of_account_active_period where pkey <> 1;
update chart_of_account_active_period set isclosed = 0;
TRUNCATE TABLE `chart_of_account_amount`;
update customer set aroutstanding = 0;
update employee set aroutstanding = 0; 
update supplier set apoutstanding = 0;
TRUNCATE TABLE `customer_downpayment_payment`;
TRUNCATE TABLE `customer_downpayment`;
TRUNCATE TABLE `general_journal_header`;
TRUNCATE TABLE `general_journal_detail`;
TRUNCATE TABLE `supplier_downpayment_payment`;
TRUNCATE TABLE `supplier_downpayment`;
TRUNCATE TABLE `trucking_cost_cash_out_header`;
TRUNCATE TABLE `trucking_cost_cash_out_file`;
TRUNCATE TABLE `trucking_cost_cash_out_detail`;
TRUNCATE TABLE `trucking_cost_cash_in_header`;
TRUNCATE TABLE `trucking_cost_cash_in_detail`;
TRUNCATE TABLE `trucking_service_work_order_cost`;
TRUNCATE TABLE `trucking_service_work_order`;
TRUNCATE TABLE `trucking_service_order_selling_cost`;
TRUNCATE TABLE `trucking_service_order_invoice_payment`;
TRUNCATE TABLE `trucking_service_order_invoice_item_detail`;
TRUNCATE TABLE `trucking_service_order_invoice_header`;
TRUNCATE TABLE `trucking_service_order_invoice_downpayment`;
TRUNCATE TABLE `trucking_service_order_invoice_detail`;
TRUNCATE TABLE `trucking_service_order_header_partial_invoice`;
TRUNCATE TABLE `trucking_service_order_header_cost`;
TRUNCATE TABLE `trucking_service_order_header`;
TRUNCATE TABLE `trucking_service_order_file`;
TRUNCATE TABLE `trucking_service_order_detail`;
truncate login_log;
truncate transaction_log;
truncate cash_advance;
TRUNCATE TABLE `cash_advance_realization_header`;
TRUNCATE TABLE `cash_advance_realization_detail`;
TRUNCATE TABLE `cash_advance_realization_advance`;
TRUNCATE TABLE `chart_of_account_counter`;
TRUNCATE TABLE `cost_reconsile_outstanding`;
TRUNCATE TABLE `cost_reconsile_header`;
TRUNCATE TABLE `cost_reconsile_detail`;
TRUNCATE TABLE `emkl_invoice_receipt_header`;
TRUNCATE TABLE `emkl_invoice_receipt_detail`;
TRUNCATE TABLE `emkl_job_order_detail_volume`;
TRUNCATE TABLE `emkl_job_order_detail_item`;
TRUNCATE TABLE `emkl_job_order_detail_container`;
TRUNCATE TABLE `emkl_job_order_detail`;
TRUNCATE TABLE `emkl_job_order_header`;
TRUNCATE TABLE `emkl_order_header`;
TRUNCATE TABLE `emkl_order_detail`;
TRUNCATE TABLE `emkl_order_invoice_downpayment`;
TRUNCATE TABLE `emkl_order_invoice_detail`;
TRUNCATE TABLE `emkl_order_header_container_detail`;
TRUNCATE TABLE `emkl_order_invoice_item_detail`;
TRUNCATE TABLE `emkl_order_invoice_header`;
TRUNCATE TABLE `emkl_purchase_order_payment`;
TRUNCATE TABLE `emkl_purchase_order_header`;
TRUNCATE TABLE `emkl_purchase_order_detail_item`;
TRUNCATE TABLE `emkl_purchase_order_detail`;
TRUNCATE TABLE `prepaid_expense`;
 


truncate `discount_scheme_detail`;
truncate `discount_scheme_header`;
