<?php
die("die, comment open for reset transaction");
include_once '../../_config.php'; 
include_once '../../_include.php';
include_once '../../_global.php';

$class->oDbCon->startTrans();

$codeFormat = '%s%05d';

$arrCompany = getDummyCompany();
$arrName = getDummyName(); 
$serviceName = getServiceName();

$dummyCtr=0;

if(DOMAIN_NAME <> 'tms.wintera.co.id') die;

$arrSQL = array();
array_push($arrSQL,'update employee set username = \'aditya\', password = \'cdf4a007e2b02a0c49fc9b7ccfbb8a10c644f635e1765dcf2a7ab794ddc7edac\' where pkey = 1 ');
array_push($arrSQL,'update _user_setting set value = \'PT. Wintera Express\' where settingkey = 3');
array_push($arrSQL,'update _user_setting set value = \'\' where settingkey = 4');
array_push($arrSQL,'update _user_setting set value = \'Jl. Savoy A1-8. Jakarta Timur.\' where settingkey = 5');
 
$rs = $customer->searchData();
foreach($rs as $key=>$row)
    array_push($arrSQL,'update '.$customer->tableName.' set name = '.$class->oDbCon->paramString($arrCompany[$dummyCtr++]).', email = \'dummy@wintera.co.id\', phone = \'021-9329999\'  where pkey = ' . $row['pkey'] );
 
$rs = $supplier->searchData();
foreach($rs as $key=>$row)
    array_push($arrSQL,'update '.$supplier->tableName.' set name = '.$class->oDbCon->paramString($arrCompany[$dummyCtr++]).', email = \'dummy@wintera.co.id\', phone = \'021-9329999\'  where pkey = ' . $row['pkey'] );

$rs = $consignee->searchData();
foreach($rs as $key=>$row)
    array_push($arrSQL,'update '.$consignee->tableName.' set name = '.$class->oDbCon->paramString($arrCompany[$dummyCtr++]).'  where pkey = ' . $row['pkey']);
 
$rs = $employee->searchData('','','',' and '.$employee->tableName.'.pkey > 1');
foreach($rs as $key=>$row)
    array_push($arrSQL,'update '.$employee->tableName.' set name = '.$class->oDbCon->paramString($arrName[$key]).'  where pkey = ' . $row['pkey']  );

$ctr = 1000;
$rs = $car->searchData();
foreach($rs as $key=>$row)
    array_push($arrSQL,'update '.$car->tableName.' set policenumber = '.$class->oDbCon->paramString('B '.$ctr++.' XY').'  where pkey = ' . $row['pkey'] );

$rs = $truckingService->searchData();
foreach($rs as $key=>$row)
    array_push($arrSQL,'update '.$truckingService->tableName.' set name = '.$class->oDbCon->paramString($serviceName[$key]).' where pkey = ' . $row['pkey'] );


$rs = $truckingServiceOrderInvoice->searchData();
foreach($rs as $key=>$row){ 
    $temp = explode('/',$row['code']);
    $newCode = sprintf($codeFormat,($row['customcodekey'] == 2) ? 'INV/WTR/' : 'RE/WTR/',$key+1);
    array_push($arrSQL,'update '.$truckingServiceOrderInvoice->tableName.' set code = '.$class->oDbCon->paramString($newCode).' where pkey = ' . $row['pkey'] );
}

$rs = $cashOut->searchData();
foreach($rs as $key=>$row)
    array_push($arrSQL,'update '.$cashOut->tableName.' set recipientname = '.$class->oDbCon->paramString($arrName[($key%100)]).'  where pkey = ' . $row['pkey']  );

$rs = $cashIn->searchData();
foreach($rs as $key=>$row)
    array_push($arrSQL,'update '.$cashIn->tableName.' set recipientname = '.$class->oDbCon->paramString($arrName[($key%100)]).'  where pkey = ' . $row['pkey']  );


/*$rs = $truckingServiceOrder->searchData(); 
foreach($rs as $key=>$row)
    array_push($arrSQL,'update '.$truckingServiceOrder->tableName.' set code = \'\'  where pkey = ' . $row['pkey']  );*/
   
array_push($arrSQL,'update cash_in_header set trdesc = ""');
array_push($arrSQL,'update cash_in_detail set trdesc = ""');
array_push($arrSQL,'update cash_out_header set trdesc = ""');
array_push($arrSQL,'update cash_out_detail set trdesc = ""');
array_push($arrSQL,'update cash_bank_transfer_header set trdesc = ""');
array_push($arrSQL,'update cash_bank_transfer_detail set trdesc = ""');
array_push($arrSQL,'update trucking_cost_cash_out_header set trdesc = "", jobdescription = ""');


array_push($arrSQL,'update ap set refcode = "", refcode2 = "", trdesc = "" ');
array_push($arrSQL,'update ar set refcode = "", refcode2 = "", trdesc = "" ');
array_push($arrSQL,'update general_journal_header set  trdesc = "", refcode = "" ');
array_push($arrSQL,'update general_journal_detail set  trdesc = "" ');

$rs = $truckingServiceWorkOrder->searchData();
foreach($rs as $key=>$row){ 
    $container1 = sprintf('%s%08d',strtoupper(substr(md5(microtime()),rand(0,26),5)),$key+1);
    $container2 = sprintf('%s%08d',strtoupper(substr(md5(microtime()),rand(0,26),5)),$key+1);
    array_push($arrSQL,'update '.$truckingServiceWorkOrder->tableName.' set code = '.$class->oDbCon->paramString(sprintf($codeFormat, 'SPK',$key+1)).', containernumber = '.$class->oDbCon->paramString($container1).' , container2number = '.$class->oDbCon->paramString($container2).' where pkey = ' . $row['pkey']  );
}


array_push($arrSQL,'truncate ar_prepaid_23');
array_push($arrSQL,'truncate ar_prepaid_23_payment');
array_push($arrSQL,'truncate ar_prepaid_23_payment_detail');
array_push($arrSQL,'truncate ar_prepaid_23_payment_header');
array_push($arrSQL,'truncate ap_payable_23');
array_push($arrSQL,'truncate ap_payable_23_payment');
array_push($arrSQL,'truncate ap_payable_23_payment_detail');
array_push($arrSQL,'truncate ap_payable_23_payment_header');

foreach($arrSQL as $sql)
    $class->oDbCon->execute($sql);

$class->oDbCon->endTrans();

echo '<bR><br>done';

 
function getServiceName(){
    
$arrName = array();
    
array_push($arrName,"Trailer 20'");
array_push($arrName,"Trailer 40'");
array_push($arrName,"Lowbed");
array_push($arrName,"Dump Truck");
array_push($arrName,"Fuso");
array_push($arrName,"Colt Diesel");
array_push($arrName,"Dolly");
    
return $arrName;    
}

function getDummyName(){

$arrName = array();
    
array_push($arrName,"Abimanyu");
array_push($arrName,"Abinaya");
array_push($arrName,"Abyasa");
array_push($arrName,"Adhi");
array_push($arrName,"Adika");
array_push($arrName,"Adinata");
array_push($arrName,"Adipramana");
array_push($arrName,"Aditya");
array_push($arrName,"Adiwangsa");
array_push($arrName,"Agam");
array_push($arrName,"Agnibrata");
array_push($arrName,"Agung");
array_push($arrName,"Aji");
array_push($arrName,"Andaru");
array_push($arrName,"Andi");
array_push($arrName,"Angkasa");
array_push($arrName,"Apta");
array_push($arrName,"Aradhana");
array_push($arrName,"Ardhi");
array_push($arrName,"Ardiyanto");
array_push($arrName,"Arga");
array_push($arrName,"Arief");
array_push($arrName,"Arjanta");
array_push($arrName,"Arya");
array_push($arrName,"Asmaralaya");
array_push($arrName,"Astaguna");
array_push($arrName,"Aswangga");
array_push($arrName,"Adiratna");
array_push($arrName,"Adriani");
array_push($arrName,"Airani");
array_push($arrName,"Amanda");
array_push($arrName,"Anatari");
array_push($arrName,"Anindya");
array_push($arrName,"Anjani");
array_push($arrName,"April");
array_push($arrName,"Arkadewi");
array_push($arrName,"Aruna");
array_push($arrName,"Arsyana");
array_push($arrName,"Asri");
array_push($arrName,"Ayu");
array_push($arrName,"Ayudisha");
array_push($arrName,"Bagas");
array_push($arrName,"Bagaskoro");
array_push($arrName,"Bajradaka");
array_push($arrName,"Bakti");
array_push($arrName,"Bamantara");
array_push($arrName,"Bambang");
array_push($arrName,"Banyu");
array_push($arrName,"Baskoro");
array_push($arrName,"Basuki");
array_push($arrName,"Baswara");
array_push($arrName,"Batara");
array_push($arrName,"Bayu");
array_push($arrName,"Bhagawanta");
array_push($arrName,"Bhanu");
array_push($arrName,"Bimo");
array_push($arrName,"Birawa");
array_push($arrName,"Bisma");
array_push($arrName,"Brahma");
array_push($arrName,"Bramantya");
array_push($arrName,"Brawijaya");
array_push($arrName,"Buana");
array_push($arrName,"Budi");
array_push($arrName,"Budiono");
array_push($arrName,"Bandiani");
array_push($arrName,"Banurasmi");
array_push($arrName,"Basagita");
array_push($arrName,"Batari");
array_push($arrName,"Binar");
array_push($arrName,"Bintang");
array_push($arrName,"Bratarini");
array_push($arrName,"Bulan");
array_push($arrName,"Cakra");
array_push($arrName,"Cakrawala");
array_push($arrName,"Candra");
array_push($arrName,"Cipta");
array_push($arrName,"Cahaya");
array_push($arrName,"Calya");
array_push($arrName,"Candramaya");
array_push($arrName,"Cempaka");
array_push($arrName,"Citra");
array_push($arrName,"Citta");
array_push($arrName,"Cyntia");
array_push($arrName,"Damar");
array_push($arrName,"Daniswara");
array_push($arrName,"Danurdara");
array_push($arrName,"Darsa");
array_push($arrName,"Dewangga");
array_push($arrName,"Dharma");
array_push($arrName,"Dipa");
array_push($arrName,"Dimas");
array_push($arrName,"Dirga");
array_push($arrName,"Danastri");
array_push($arrName,"Danurdara");
array_push($arrName,"Dewi");
array_push($arrName,"Dhatu");
array_push($arrName,"Diajeng");
array_push($arrName,"Dianti");
array_push($arrName,"Diatmika");
array_push($arrName,"Ditya");
array_push($arrName,"Dwi");
array_push($arrName,"Edi");
array_push($arrName,"Endaru");
array_push($arrName,"Estu");
array_push($arrName,"Endang");
array_push($arrName,"Gadhing");
array_push($arrName,"Ganendra");
array_push($arrName,"Gardara");
array_push($arrName,"Gentala");
array_push($arrName,"Galih");
array_push($arrName,"Ganesh");
array_push($arrName,"Gibran");
array_push($arrName,"Gilang");
array_push($arrName,"Guinandra");
array_push($arrName,"Gumelar");
array_push($arrName,"Gunawan");
array_push($arrName,"Guntur");
array_push($arrName,"Guritno");
array_push($arrName,"Gusti");
array_push($arrName,"Gadis");
array_push($arrName,"Gahyaka");
array_push($arrName,"Gantari");
array_push($arrName,"Garini");
array_push($arrName,"Gayatri");
array_push($arrName,"Gema");
array_push($arrName,"Gemani");
array_push($arrName,"Gemintang");
array_push($arrName,"Gempita");
array_push($arrName,"Genta");
array_push($arrName,"Ginanita");
array_push($arrName,"Gyandra");
array_push($arrName,"Hadi");
array_push($arrName,"Hakim");
array_push($arrName,"Halim");
array_push($arrName,"Hamdan");
array_push($arrName,"Hanafi");
array_push($arrName,"Handaru");
array_push($arrName,"Hapsari");
array_push($arrName,"Hardana");
array_push($arrName,"Haribawa");
array_push($arrName,"Haris");
array_push($arrName,"Harjita");
array_push($arrName,"Hartadi");
array_push($arrName,"Hartanto");
array_push($arrName,"Haryanto");
array_push($arrName,"Hasta");
array_push($arrName,"Hendro");
array_push($arrName,"Herdian");
array_push($arrName,"Herjuno");
array_push($arrName,"Henry");
array_push($arrName,"Hery");
array_push($arrName,"Haira");
array_push($arrName,"Hanasta");
array_push($arrName,"Hanna");
array_push($arrName,"Harini");
array_push($arrName,"Hasana");
array_push($arrName,"Hasya");
array_push($arrName,"Hayu");
array_push($arrName,"Kahyang");
array_push($arrName,"Kamala");
array_push($arrName,"Kana");
array_push($arrName,"Kani");
array_push($arrName,"Kanista");
array_push($arrName,"Karina");
array_push($arrName,"Karmika");
array_push($arrName,"Kartana");
array_push($arrName,"Kasidya");
array_push($arrName,"Kasih");
array_push($arrName,"Kasyaira");
array_push($arrName,"Kayshila");
array_push($arrName,"Keinan");
array_push($arrName,"Kemala");
array_push($arrName,"Kencana");
array_push($arrName,"Keswari");
array_push($arrName,"Kila");
array_push($arrName,"Kinnas");
array_push($arrName,"Kirana");
    
return $arrName;
}

function getDummyCompany(){
$arrCompany = array();    
array_push($arrCompany,"PT Siregar Maheswara");
array_push($arrCompany,"UD Puspita Nasyiah");
array_push($arrCompany,"CV Wijaya Wahyuni (Persero) Tbk");
array_push($arrCompany,"UD Astuti");
array_push($arrCompany,"CV Thamrin Budiyanto Tbk");
array_push($arrCompany,"UD Pertiwi");
array_push($arrCompany,"PD Sihotang");
array_push($arrCompany,"Perum Prakasa Farida");
array_push($arrCompany,"Perum Putra");
array_push($arrCompany,"Perum Sirait");
array_push($arrCompany,"PD Namaga");
array_push($arrCompany,"CV Haryanto Salahudin");
array_push($arrCompany,"PT Wahyuni Purwanti");
array_push($arrCompany,"CV Marbun Prasetyo Tbk");
array_push($arrCompany,"Perum Pradipta Yulianti (Persero) Tbk");
array_push($arrCompany,"PT Kusmawati Ramadan Tbk");
array_push($arrCompany,"CV Laksita Dabukke (Persero) Tbk");
array_push($arrCompany,"Perum Suryatmi Sihombing");
array_push($arrCompany,"Perum Marbun Tbk");
array_push($arrCompany,"UD Suartini (Persero) Tbk");
array_push($arrCompany,"PT Thamrin Yuliarti");
array_push($arrCompany,"PT Hartati Usamah");
array_push($arrCompany,"UD Novitasari Hassanah Tbk");
array_push($arrCompany,"Perum Siregar Utama (Persero) Tbk");
array_push($arrCompany,"PT Rajasa (Persero) Tbk");
array_push($arrCompany,"PD Handayani Novitasari");
array_push($arrCompany,"PD Wulandari Winarsih Tbk");
array_push($arrCompany,"PT Siregar Damanik Tbk");
array_push($arrCompany,"UD Mulyani Sudiati Tbk");
array_push($arrCompany,"Perum Permadi Hutasoit (Persero) Tbk");
array_push($arrCompany,"UD Wijaya (Persero) Tbk");
array_push($arrCompany,"PD Simanjuntak Wasita");
array_push($arrCompany,"PT Manullang Wahyuni Tbk");
array_push($arrCompany,"CV Gunawan Maheswara (Persero) Tbk");
array_push($arrCompany,"PT Saptono Simanjuntak");
array_push($arrCompany,"PD Haryanti (Persero) Tbk");
array_push($arrCompany,"CV Tamba Iswahyudi");
array_push($arrCompany,"Perum Pratama Anggriawan (Persero) Tbk");
array_push($arrCompany,"CV Manullang Suartini Tbk");
array_push($arrCompany,"UD Saptono (Persero) Tbk");
array_push($arrCompany,"UD Hasanah Uwais");
array_push($arrCompany,"Perum Agustina");
array_push($arrCompany,"UD Utama Wahyuni");
array_push($arrCompany,"Perum Nasyidah");
array_push($arrCompany,"PT Prasetyo");
array_push($arrCompany,"Perum Purnawati");
array_push($arrCompany,"UD Winarno Tbk");
array_push($arrCompany,"Perum Kuswandari");
array_push($arrCompany,"PD Suryatmi Najmudin");
array_push($arrCompany,"Perum Maulana Tbk");
array_push($arrCompany,"CV Tamba Oktaviani");
array_push($arrCompany,"PT Winarsih Pudjiastuti");
array_push($arrCompany,"UD Namaga");
array_push($arrCompany,"Perum Najmudin");
array_push($arrCompany,"PT Nasyiah Purwanti");
array_push($arrCompany,"PT Permadi Hidayat (Persero) Tbk");
array_push($arrCompany,"CV Yuliarti Tbk");
array_push($arrCompany,"PD Sudiati (Persero) Tbk");
array_push($arrCompany,"Perum Wijayanti Suryono");
array_push($arrCompany,"CV Setiawan Mahendra");
array_push($arrCompany,"Perum Najmudin Tbk");
array_push($arrCompany,"UD Adriansyah Lazuardi");
array_push($arrCompany,"PD Pradipta (Persero) Tbk");
array_push($arrCompany,"Perum Nababan (Persero) Tbk");
array_push($arrCompany,"PD Lazuardi Nugroho Tbk");
array_push($arrCompany,"PD Pradipta");
array_push($arrCompany,"PT Saptono Tbk");
array_push($arrCompany,"Perum Wahyuni");
array_push($arrCompany,"PD Laksita");
array_push($arrCompany,"PT Oktaviani Andriani Tbk");
array_push($arrCompany,"CV Anggraini (Persero) Tbk");
array_push($arrCompany,"UD Hariyah Budiman");
array_push($arrCompany,"Perum Wijayanti");
array_push($arrCompany,"PT Uyainah Sudiati (Persero) Tbk");
array_push($arrCompany,"CV Mustofa");
array_push($arrCompany,"PD Wijayanti Laksita");
array_push($arrCompany,"PD Pranowo");
array_push($arrCompany,"UD Rahayu Mangunsong Tbk");
array_push($arrCompany,"PD Wulandari Wijayanti Tbk");
array_push($arrCompany,"CV Yulianti Safitri");
array_push($arrCompany,"Perum Ardianto Tbk");
array_push($arrCompany,"UD Nurdiyanti (Persero) Tbk");
array_push($arrCompany,"PT Wijaya");
array_push($arrCompany,"PD Susanti Halim");
array_push($arrCompany,"UD Yuniar");
array_push($arrCompany,"CV Salahudin Nuraini");
array_push($arrCompany,"PT Agustina Mandala");
array_push($arrCompany,"UD Januar Suartini");
array_push($arrCompany,"PD Marbun Pradana (Persero) Tbk");
array_push($arrCompany,"CV Novitasari Winarno Tbk");
array_push($arrCompany,"PT Hidayanto Firgantoro");
array_push($arrCompany,"PT Prastuti");
array_push($arrCompany,"UD Pratiwi Widodo (Persero) Tbk");
array_push($arrCompany,"CV Mahendra (Persero) Tbk");
array_push($arrCompany,"Perum Sihombing");
array_push($arrCompany,"CV Samosir Mansur (Persero) Tbk");
array_push($arrCompany,"PT Suryatmi Saragih");
array_push($arrCompany,"PD Tarihoran");
array_push($arrCompany,"UD Rajata (Persero) Tbk");
array_push($arrCompany,"PD Wibowo");
array_push($arrCompany,"PD Santoso Halimah (Persero) Tbk");
array_push($arrCompany,"PD Narpati Dongoran");
array_push($arrCompany,"Perum Farida Mandala");
array_push($arrCompany,"PT Purnawati Firmansyah");
array_push($arrCompany,"PT Halim Pertiwi");
array_push($arrCompany,"Perum Widodo");
array_push($arrCompany,"PD Purnawati Suartini (Persero) Tbk");
array_push($arrCompany,"PT Irawan");
array_push($arrCompany,"Perum Novitasari Tbk");
array_push($arrCompany,"Perum Rahimah Hutasoit");
array_push($arrCompany,"PD Puspita Wijaya (Persero) Tbk");
array_push($arrCompany,"CV Hutapea Hutagalung");
array_push($arrCompany,"PD Zulkarnain (Persero) Tbk");
array_push($arrCompany,"PD Prasetyo");
array_push($arrCompany,"PT Hariyah");
array_push($arrCompany,"PD Maulana Tbk");
array_push($arrCompany,"PD Padmasari");
array_push($arrCompany,"PD Wijayanti");
array_push($arrCompany,"UD Mayasari Maulana");
array_push($arrCompany,"UD Rahmawati");
array_push($arrCompany,"Perum Dongoran Sitompul (Persero) Tbk");
array_push($arrCompany,"PT Hakim Safitri");
array_push($arrCompany,"UD Aryani Laksita");
array_push($arrCompany,"PD Suryono Zulaika");
array_push($arrCompany,"UD Pudjiastuti Purwanti");
array_push($arrCompany,"UD Prasetya");
array_push($arrCompany,"CV Haryanti Mandala (Persero) Tbk");
array_push($arrCompany,"PD Maryati Rahayu");
array_push($arrCompany,"CV Hutagalung");
array_push($arrCompany,"PD Wastuti Pangestu Tbk");
array_push($arrCompany,"UD Kuswandari");
array_push($arrCompany,"PT Pudjiastuti Purwanti");
array_push($arrCompany,"CV Situmorang (Persero) Tbk");
array_push($arrCompany,"PT Usada (Persero) Tbk");
array_push($arrCompany,"PD Palastri Lailasari (Persero) Tbk");
array_push($arrCompany,"CV Winarsih");
array_push($arrCompany,"CV Nababan (Persero) Tbk");
array_push($arrCompany,"PT Wahyuni");
array_push($arrCompany,"PD Waskita");
array_push($arrCompany,"Perum Nuraini Prastuti");
array_push($arrCompany,"UD Maryadi Tarihoran");
array_push($arrCompany,"CV Novitasari Laksmiwati");
array_push($arrCompany,"CV Rahmawati");
array_push($arrCompany,"PD Handayani Novitasari");
array_push($arrCompany,"UD Padmasari Haryanto");
array_push($arrCompany,"Perum Utami Hassanah");
array_push($arrCompany,"CV Maheswara");
array_push($arrCompany,"Perum Utami Mandala (Persero) Tbk");
array_push($arrCompany,"Perum Hastuti Hasanah Tbk");
array_push($arrCompany,"UD Rahayu");
array_push($arrCompany,"CV Haryanto Riyanti");
array_push($arrCompany,"CV Nainggolan Wahyudin");
array_push($arrCompany,"PD Aryani Pertiwi Tbk");
array_push($arrCompany,"Perum Budiman Suwarno");
array_push($arrCompany,"PT Sitorus Firgantoro");
array_push($arrCompany,"PT Hassanah Narpati");
array_push($arrCompany,"CV Siregar Farida");
array_push($arrCompany,"Perum Yulianti");
array_push($arrCompany,"UD Hastuti (Persero) Tbk");
array_push($arrCompany,"PD Kuswandari Novitasari (Persero) Tbk");
array_push($arrCompany,"PD Halim Tbk");
array_push($arrCompany,"CV Rahimah (Persero) Tbk");
array_push($arrCompany,"CV Hastuti Prayoga Tbk");
array_push($arrCompany,"CV Saputra Nasyidah");
array_push($arrCompany,"Perum Nashiruddin");
array_push($arrCompany,"UD Purwanti Mandasari (Persero) Tbk");
array_push($arrCompany,"CV Nashiruddin Farida");
array_push($arrCompany,"CV Winarno");
array_push($arrCompany,"PD Aryani Utama (Persero) Tbk");
array_push($arrCompany,"UD Palastri");
array_push($arrCompany,"UD Sitorus");
array_push($arrCompany,"PD Laksmiwati");
array_push($arrCompany,"UD Wastuti (Persero) Tbk");
array_push($arrCompany,"Perum Sihombing Tbk");
array_push($arrCompany,"PT Najmudin (Persero) Tbk");
array_push($arrCompany,"UD Haryanti (Persero) Tbk");
array_push($arrCompany,"Perum Uyainah Tbk");
array_push($arrCompany,"PD Yolanda Suartini Tbk");
array_push($arrCompany,"PT Laksita Widiastuti Tbk");
array_push($arrCompany,"CV Saptono Mangunsong (Persero) Tbk");
array_push($arrCompany,"UD Hartati Prasetya");
array_push($arrCompany,"Perum Sihotang Prakasa (Persero) Tbk");
array_push($arrCompany,"PT Padmasari Halim");
array_push($arrCompany,"CV Nababan Nababan");
array_push($arrCompany,"PT Zulkarnain (Persero) Tbk");
array_push($arrCompany,"UD Wijayanti Haryanti Tbk");
array_push($arrCompany,"Perum Hariyah Oktaviani");
array_push($arrCompany,"Perum Palastri");
array_push($arrCompany,"UD Putra Widodo Tbk");
array_push($arrCompany,"PT Nuraini");
array_push($arrCompany,"CV Wibowo Yuniar (Persero) Tbk");
array_push($arrCompany,"UD Halimah Melani");
array_push($arrCompany,"PD Agustina (Persero) Tbk");
array_push($arrCompany,"PD Winarsih Mardhiyah Tbk");
array_push($arrCompany,"UD Pangestu Prasasta (Persero) Tbk");
array_push($arrCompany,"Perum Novitasari Usada Tbk");
array_push($arrCompany,"CV Ardianto");
array_push($arrCompany,"Perum Melani Habibi (Persero) Tbk");
array_push($arrCompany,"PT Riyanti");
array_push($arrCompany,"Perum Manullang");
array_push($arrCompany,"Perum Mardhiyah Tbk");
array_push($arrCompany,"UD Halim Agustina");
array_push($arrCompany,"PT Simanjuntak (Persero) Tbk");
array_push($arrCompany,"PD Iswahyudi (Persero) Tbk");
array_push($arrCompany,"Perum Wasita Tarihoran");
array_push($arrCompany,"UD Laksmiwati Putra Tbk");
array_push($arrCompany,"PD Mulyani (Persero) Tbk");
array_push($arrCompany,"PT Pradipta (Persero) Tbk");
array_push($arrCompany,"PT Marpaung Wijaya Tbk");
array_push($arrCompany,"PD Wijaya Tbk");
array_push($arrCompany,"UD Purnawati");
array_push($arrCompany,"PD Kusmawati Tbk");
array_push($arrCompany,"Perum Aryani Tbk");
array_push($arrCompany,"Perum Hutasoit Hidayat");
array_push($arrCompany,"PD Tarihoran Puspasari (Persero) Tbk");
array_push($arrCompany,"PD Sitompul Wahyuni Tbk");
array_push($arrCompany,"CV Prabowo (Persero) Tbk");
array_push($arrCompany,"UD Hidayanto (Persero) Tbk");
array_push($arrCompany,"Perum Wijaya (Persero) Tbk");
array_push($arrCompany,"CV Tampubolon Tbk");
array_push($arrCompany,"UD Gunawan");
array_push($arrCompany,"PD Mangunsong Tbk");
array_push($arrCompany,"PD Winarno (Persero) Tbk");
array_push($arrCompany,"CV Mayasari");
array_push($arrCompany,"Perum Hartati (Persero) Tbk");
array_push($arrCompany,"PT Simbolon Hutasoit Tbk");
array_push($arrCompany,"Perum Lazuardi Prastuti");
array_push($arrCompany,"CV Puspasari");
array_push($arrCompany,"PT Hutapea");
array_push($arrCompany,"PD Simbolon Tbk");
array_push($arrCompany,"PT Hakim Melani");
array_push($arrCompany,"UD Nasyidah Prastuti");
array_push($arrCompany,"CV Simanjuntak Nababan (Persero) Tbk");
array_push($arrCompany,"CV Mayasari Rahmawati Tbk");
array_push($arrCompany,"CV Firmansyah (Persero) Tbk");
array_push($arrCompany,"PT Pradana");
array_push($arrCompany,"Perum Uyainah");
array_push($arrCompany,"PT Astuti");
array_push($arrCompany,"PT Mardhiyah");
array_push($arrCompany,"UD Mulyani Pradipta (Persero) Tbk");
array_push($arrCompany,"PD Palastri Haryanti Tbk");
array_push($arrCompany,"UD Sudiati Yuliarti (Persero) Tbk");
array_push($arrCompany,"PT Melani");
array_push($arrCompany,"PT Wahyuni");
array_push($arrCompany,"PD Rahmawati Prasetya (Persero) Tbk");
array_push($arrCompany,"UD Wasita");
array_push($arrCompany,"UD Wijaya");
array_push($arrCompany,"PD Uwais");
array_push($arrCompany,"CV Wibowo Mustofa");
array_push($arrCompany,"CV Laksita");
array_push($arrCompany,"PT Sudiati");
array_push($arrCompany,"PD Hutasoit Tbk");
array_push($arrCompany,"UD Namaga Permadi Tbk");
array_push($arrCompany,"CV Purnawati Wahyuni (Persero) Tbk");
array_push($arrCompany,"UD Maheswara Halim");
array_push($arrCompany,"CV Pangestu Winarsih");
array_push($arrCompany,"PD Astuti Widodo (Persero) Tbk");
array_push($arrCompany,"PD Kusmawati");
array_push($arrCompany,"CV Utami");
array_push($arrCompany,"PT Rajasa (Persero) Tbk");
array_push($arrCompany,"Perum Firgantoro (Persero) Tbk");
array_push($arrCompany,"Perum Prastuti Nasyiah");
array_push($arrCompany,"CV Tarihoran Hakim");
array_push($arrCompany,"UD Mardhiyah Dabukke");
array_push($arrCompany,"CV Uyainah (Persero) Tbk");
array_push($arrCompany,"PT Hardiansyah Zulkarnain (Persero) Tbk");
array_push($arrCompany,"CV Astuti Mandala (Persero) Tbk");
array_push($arrCompany,"CV Lestari Yolanda");
array_push($arrCompany,"CV Nashiruddin (Persero) Tbk");
array_push($arrCompany,"CV Hassanah Hidayat Tbk");
array_push($arrCompany,"UD Fujiati Tbk");
array_push($arrCompany,"PT Sitorus (Persero) Tbk");
array_push($arrCompany,"Perum Lestari");
array_push($arrCompany,"PD Wijaya Halim");
array_push($arrCompany,"Perum Budiman Yuniar Tbk");
array_push($arrCompany,"Perum Riyanti Sitorus");
array_push($arrCompany,"PT Prayoga Safitri Tbk");
array_push($arrCompany,"Perum Padmasari Laksmiwati (Persero) Tbk");
array_push($arrCompany,"CV Januar (Persero) Tbk");
array_push($arrCompany,"PT Nasyiah Tamba");
array_push($arrCompany,"PT Prasasta Padmasari");
array_push($arrCompany,"Perum Wasita Pangestu Tbk");
array_push($arrCompany,"PD Saragih");
array_push($arrCompany,"PT Maheswara Tbk");
array_push($arrCompany,"PT Prasasta Suryatmi (Persero) Tbk");
array_push($arrCompany,"UD Puspita (Persero) Tbk");
array_push($arrCompany,"CV Pudjiastuti Halimah");
array_push($arrCompany,"Perum Wastuti Tbk");
array_push($arrCompany,"Perum Waluyo Riyanti");
array_push($arrCompany,"PT Siregar Anggraini Tbk");
array_push($arrCompany,"Perum Oktaviani Irawan");
array_push($arrCompany,"UD Oktaviani Utama");
array_push($arrCompany,"PT Waluyo (Persero) Tbk");
array_push($arrCompany,"CV Sihombing Tbk");
array_push($arrCompany,"UD Waskita (Persero) Tbk");
array_push($arrCompany,"UD Waluyo");
array_push($arrCompany,"PT Hariyah");
array_push($arrCompany,"Perum Sihombing Permadi (Persero) Tbk");
array_push($arrCompany,"Perum Wahyuni");
array_push($arrCompany,"PT Saptono Aryani (Persero) Tbk");
array_push($arrCompany,"CV Wasita Tbk");
array_push($arrCompany,"CV Suryono");
array_push($arrCompany,"UD Prakasa (Persero) Tbk");
array_push($arrCompany,"PD Hakim Maryati Tbk");
array_push($arrCompany,"PT Astuti Simbolon Tbk");
array_push($arrCompany,"Perum Yuliarti Sihotang (Persero) Tbk");
array_push($arrCompany,"PT Rahimah Lestari Tbk");
array_push($arrCompany,"Perum Nababan Rajasa");
array_push($arrCompany,"UD Anggraini Susanti (Persero) Tbk");
array_push($arrCompany,"PD Utami Widiastuti");
array_push($arrCompany,"PD Andriani Agustina");
array_push($arrCompany,"UD Suryono Rahmawati Tbk");
array_push($arrCompany,"Perum Budiyanto Laksmiwati Tbk");
array_push($arrCompany,"UD Anggraini");
array_push($arrCompany,"PD Hartati");
array_push($arrCompany,"UD Yulianti Winarno");
array_push($arrCompany,"Perum Suartini");
array_push($arrCompany,"UD Yuliarti");
array_push($arrCompany,"PT Nuraini");
array_push($arrCompany,"PD Uwais Lailasari");
array_push($arrCompany,"UD Wahyudin Zulaika Tbk");
array_push($arrCompany,"CV Tampubolon Pradipta (Persero) Tbk");
array_push($arrCompany,"CV Winarsih Rahmawati");
array_push($arrCompany,"PT Siregar");
array_push($arrCompany,"PT Thamrin Sitompul");
array_push($arrCompany,"CV Putra Tbk");
array_push($arrCompany,"PT Adriansyah Laksmiwati");
array_push($arrCompany,"Perum Sihotang Suartini (Persero) Tbk");
array_push($arrCompany,"Perum Iswahyudi Natsir");
array_push($arrCompany,"CV Namaga");
array_push($arrCompany,"PT Maheswara Siregar Tbk");
array_push($arrCompany,"CV Prakasa Firmansyah (Persero) Tbk");
array_push($arrCompany,"CV Hardiansyah Januar (Persero) Tbk");
array_push($arrCompany,"PD Yolanda Nashiruddin");
array_push($arrCompany,"PT Sudiati Fujiati");
array_push($arrCompany,"Perum Waluyo");
array_push($arrCompany,"CV Prastuti Yulianti");
array_push($arrCompany,"PD Kuswandari Tbk");
array_push($arrCompany,"UD Utama");
array_push($arrCompany,"PD Pangestu Hartati Tbk");
array_push($arrCompany,"PD Simanjuntak Pertiwi Tbk");
array_push($arrCompany,"PD Kuswandari Permadi");
array_push($arrCompany,"PT Padmasari");
array_push($arrCompany,"PT Prasasta (Persero) Tbk");
array_push($arrCompany,"CV Haryanti");
array_push($arrCompany,"CV Haryanto");
array_push($arrCompany,"PD Palastri Suartini");
array_push($arrCompany,"CV Wulandari Rahimah (Persero) Tbk");
array_push($arrCompany,"PT Kuswandari");
array_push($arrCompany,"UD Utami");
array_push($arrCompany,"Perum Kuswandari");
array_push($arrCompany,"PT Andriani Narpati (Persero) Tbk");
array_push($arrCompany,"PD Maulana Usada");
array_push($arrCompany,"Perum Widiastuti (Persero) Tbk");
array_push($arrCompany,"Perum Hartati Mayasari Tbk");
array_push($arrCompany,"Perum Waluyo Tamba");
array_push($arrCompany,"PT Nainggolan Nasyidah");
array_push($arrCompany,"Perum Jailani");
array_push($arrCompany,"Perum Yulianti");
array_push($arrCompany,"PT Irawan (Persero) Tbk");
array_push($arrCompany,"PD Agustina Nuraini Tbk");
array_push($arrCompany,"PD Laksmiwati");
array_push($arrCompany,"UD Sihombing");
array_push($arrCompany,"Perum Yolanda");
array_push($arrCompany,"UD Napitupulu");
array_push($arrCompany,"PT Mahendra");
array_push($arrCompany,"UD Pudjiastuti Pranowo");
array_push($arrCompany,"PT Nugroho Winarsih Tbk");
array_push($arrCompany,"CV Farida Prakasa Tbk");
array_push($arrCompany,"Perum Hariyah (Persero) Tbk");
array_push($arrCompany,"CV Rahimah");
array_push($arrCompany,"PD Prastuti");
array_push($arrCompany,"PD Andriani Tbk");
array_push($arrCompany,"PD Adriansyah");
array_push($arrCompany,"PT Winarsih Nasyidah Tbk");
array_push($arrCompany,"UD Prakasa Maheswara (Persero) Tbk");
array_push($arrCompany,"PD Melani (Persero) Tbk");
array_push($arrCompany,"Perum Sinaga Namaga");
array_push($arrCompany,"PT Wibisono");
array_push($arrCompany,"PD Zulaika");
array_push($arrCompany,"UD Andriani");
array_push($arrCompany,"PD Hutapea");
array_push($arrCompany,"CV Novitasari Purwanti");
array_push($arrCompany,"PT Pertiwi Tbk");
array_push($arrCompany,"CV Usamah Mansur");
array_push($arrCompany,"CV Yolanda Firgantoro Tbk");
array_push($arrCompany,"PD Simbolon Marpaung (Persero) Tbk");
array_push($arrCompany,"Perum Agustina Suartini Tbk");
array_push($arrCompany,"PD Permadi (Persero) Tbk");
array_push($arrCompany,"UD Yulianti (Persero) Tbk");
array_push($arrCompany,"Perum Utama Kusmawati Tbk");
array_push($arrCompany,"CV Susanti (Persero) Tbk");
array_push($arrCompany,"UD Nainggolan Prasetya Tbk");
array_push($arrCompany,"PD Zulkarnain Zulkarnain");
array_push($arrCompany,"PT Halimah (Persero) Tbk");
array_push($arrCompany,"PD Maryati Tbk");
array_push($arrCompany,"PT Rahmawati Kurniawan");
array_push($arrCompany,"UD Tarihoran Mangunsong (Persero) Tbk");
array_push($arrCompany,"UD Riyanti (Persero) Tbk");
array_push($arrCompany,"CV Puspita Tbk");
array_push($arrCompany,"PD Wibowo Lailasari (Persero) Tbk");
array_push($arrCompany,"UD Hutapea Hakim");
array_push($arrCompany,"PD Pradipta Tbk");
array_push($arrCompany,"PT Napitupulu");
array_push($arrCompany,"CV Hutasoit Prastuti");
array_push($arrCompany,"CV Mulyani Susanti Tbk");
array_push($arrCompany,"UD Hartati Waskita");
array_push($arrCompany,"Perum Lazuardi Tbk");
array_push($arrCompany,"PT Usada Wahyuni Tbk");
array_push($arrCompany,"PD Lazuardi Rajasa");
array_push($arrCompany,"UD Melani");
array_push($arrCompany,"Perum Mardhiyah (Persero) Tbk");
array_push($arrCompany,"UD Lestari Pradana (Persero) Tbk");
array_push($arrCompany,"PT Gunawan");
array_push($arrCompany,"PT Yolanda Winarno");
array_push($arrCompany,"Perum Wasita Halimah");
array_push($arrCompany,"PD Maryati Pranowo (Persero) Tbk");
array_push($arrCompany,"PD Yuliarti Kuswandari Tbk");
array_push($arrCompany,"UD Hutagalung Laksmiwati (Persero) Tbk");
array_push($arrCompany,"PT Wijayanti Tbk");
array_push($arrCompany,"Perum Yulianti Tbk");
array_push($arrCompany,"PD Kusmawati");
array_push($arrCompany,"PT Fujiati Tbk");
array_push($arrCompany,"UD Sitompul Gunawan (Persero) Tbk");
array_push($arrCompany,"UD Waskita Nasyiah (Persero) Tbk");
array_push($arrCompany,"UD Kusmawati (Persero) Tbk");
array_push($arrCompany,"Perum Wulandari Wibisono");
array_push($arrCompany,"PT Rajasa");
array_push($arrCompany,"PD Nurdiyanti");
array_push($arrCompany,"UD Laksmiwati Tbk");
array_push($arrCompany,"UD Usamah");
array_push($arrCompany,"CV Uwais Mayasari (Persero) Tbk");
array_push($arrCompany,"PD Suwarno Puspita");
array_push($arrCompany,"PD Kusumo Firmansyah (Persero) Tbk");
array_push($arrCompany,"Perum Latupono");
array_push($arrCompany,"PT Samosir Puspasari Tbk");
array_push($arrCompany,"UD Winarsih Ardianto");
array_push($arrCompany,"Perum Prayoga");
array_push($arrCompany,"CV Anggraini");
array_push($arrCompany,"PD Laksmiwati Nasyiah (Persero) Tbk");
array_push($arrCompany,"PT Wastuti");
array_push($arrCompany,"PT Melani Tbk");
array_push($arrCompany,"PT Marpaung Napitupulu");
array_push($arrCompany,"CV Wasita");
array_push($arrCompany,"PD Usamah");
array_push($arrCompany,"UD Kusumo");
array_push($arrCompany,"UD Maulana");
array_push($arrCompany,"Perum Dabukke Wulandari Tbk");
array_push($arrCompany,"Perum Hidayanto Kurniawan Tbk");
array_push($arrCompany,"Perum Usamah Tbk");
array_push($arrCompany,"CV Sitompul (Persero) Tbk");
array_push($arrCompany,"UD Maheswara (Persero) Tbk");
array_push($arrCompany,"UD Firgantoro");
array_push($arrCompany,"Perum Melani");
array_push($arrCompany,"CV Saragih Puspasari");
array_push($arrCompany,"Perum Mandasari Farida (Persero) Tbk");
array_push($arrCompany,"UD Latupono");
array_push($arrCompany,"PD Sudiati");
array_push($arrCompany,"UD Susanti Nurdiyanti Tbk");
array_push($arrCompany,"UD Sihombing");
array_push($arrCompany,"Perum Pratama Astuti (Persero) Tbk");
array_push($arrCompany,"PD Gunawan");
array_push($arrCompany,"UD Mansur Kuswandari");
array_push($arrCompany,"CV Napitupulu Novitasari Tbk");
array_push($arrCompany,"PD Prasasta");
array_push($arrCompany,"Perum Marpaung");
array_push($arrCompany,"PT Kusmawati Hartati (Persero) Tbk");
array_push($arrCompany,"UD Hasanah Suartini (Persero) Tbk");
array_push($arrCompany,"PT Prakasa Siregar Tbk");
array_push($arrCompany,"PD Hassanah Wastuti (Persero) Tbk");
array_push($arrCompany,"PD Hutasoit Lailasari");
array_push($arrCompany,"PT Farida (Persero) Tbk");
array_push($arrCompany,"Perum Susanti Setiawan Tbk");
array_push($arrCompany,"PD Puspasari Tbk");
array_push($arrCompany,"Perum Firmansyah (Persero) Tbk");
array_push($arrCompany,"PT Agustina (Persero) Tbk");
array_push($arrCompany,"PD Agustina");
array_push($arrCompany,"UD Yuniar");
array_push($arrCompany,"CV Sihombing Dongoran");
array_push($arrCompany,"PT Natsir");
array_push($arrCompany,"UD Budiman Sudiati Tbk");
array_push($arrCompany,"Perum Lazuardi Andriani Tbk");
array_push($arrCompany,"Perum Usada Tbk");
array_push($arrCompany,"PD Permata Tbk");
array_push($arrCompany,"PT Ramadan (Persero) Tbk");
array_push($arrCompany,"Perum Sirait Hastuti (Persero) Tbk");
array_push($arrCompany,"PT Kusumo (Persero) Tbk");
array_push($arrCompany,"PT Lailasari Sitompul");
array_push($arrCompany,"PT Namaga Megantara");
array_push($arrCompany,"CV Budiyanto Simanjuntak");
array_push($arrCompany,"CV Irawan Usada");
array_push($arrCompany,"UD Puspasari");
array_push($arrCompany,"CV Rahmawati");
array_push($arrCompany,"PT Winarsih (Persero) Tbk");
array_push($arrCompany,"UD Lestari");
array_push($arrCompany,"PT Nuraini Kuswoyo (Persero) Tbk");
array_push($arrCompany,"PD Nuraini");
array_push($arrCompany,"Perum Rahimah Tbk");
array_push($arrCompany,"UD Uyainah Hariyah (Persero) Tbk");
array_push($arrCompany,"UD Wibisono");
array_push($arrCompany,"PD Palastri Permadi");
array_push($arrCompany,"UD Wasita Situmorang");
array_push($arrCompany,"PD Kuswoyo");
array_push($arrCompany,"UD Namaga Pradipta");
array_push($arrCompany,"UD Rajasa Nasyidah Tbk");
array_push($arrCompany,"PD Melani Rajasa");
array_push($arrCompany,"CV Agustina Dongoran Tbk");
array_push($arrCompany,"UD Kuswoyo Lestari (Persero) Tbk");
array_push($arrCompany,"PD Rahmawati Laksmiwati");
array_push($arrCompany,"CV Waluyo (Persero) Tbk");
array_push($arrCompany,"CV Wijaya Suryono");
array_push($arrCompany,"UD Lestari Tbk");
array_push($arrCompany,"Perum Laksmiwati Rahmawati");
array_push($arrCompany,"CV Susanti");
array_push($arrCompany,"Perum Uwais Wijayanti Tbk");
array_push($arrCompany,"PT Pudjiastuti Haryanti");
array_push($arrCompany,"UD Rajasa");
array_push($arrCompany,"PT Rahmawati (Persero) Tbk");
array_push($arrCompany,"PT Najmudin Tbk");
array_push($arrCompany,"UD Ramadan");
array_push($arrCompany,"Perum Rahmawati Hariyah Tbk");
array_push($arrCompany,"PT Uwais");
array_push($arrCompany,"UD Mulyani");
array_push($arrCompany,"CV Tamba Astuti (Persero) Tbk");
array_push($arrCompany,"CV Sitorus (Persero) Tbk");
array_push($arrCompany,"PT Sitorus Tbk");
array_push($arrCompany,"Perum Puspita Hassanah");
array_push($arrCompany,"Perum Mangunsong Wastuti (Persero) Tbk");
array_push($arrCompany,"CV Anggraini");
array_push($arrCompany,"UD Sihombing");
array_push($arrCompany,"UD Salahudin");
array_push($arrCompany,"PD Halimah Hakim");
array_push($arrCompany,"Perum Halimah Safitri");
array_push($arrCompany,"UD Setiawan Usamah");
array_push($arrCompany,"CV Mandasari Widiastuti");
array_push($arrCompany,"UD Nashiruddin");
array_push($arrCompany,"PT Widiastuti Halim (Persero) Tbk");
array_push($arrCompany,"Perum Farida Sitompul");
array_push($arrCompany,"PT Prayoga Tbk");
array_push($arrCompany,"PT Prasetya Saragih (Persero) Tbk");
array_push($arrCompany,"PT Handayani Oktaviani Tbk");
array_push($arrCompany,"PT Usamah");
array_push($arrCompany,"UD Oktaviani Prakasa");
array_push($arrCompany,"Perum Najmudin Hidayanto Tbk");
array_push($arrCompany,"Perum Suwarno Agustina");
array_push($arrCompany,"PT Handayani");
array_push($arrCompany,"PD Anggriawan");
array_push($arrCompany,"Perum Hassanah Widiastuti (Persero) Tbk");
array_push($arrCompany,"Perum Jailani");
array_push($arrCompany,"PD Haryanti (Persero) Tbk");
array_push($arrCompany,"PD Winarsih");
array_push($arrCompany,"Perum Wastuti Uyainah");
array_push($arrCompany,"CV Napitupulu Anggriawan");
array_push($arrCompany,"PT Mardhiyah Tbk");
array_push($arrCompany,"Perum Wibisono Firgantoro");
array_push($arrCompany,"CV Prasasta Sihotang Tbk");
array_push($arrCompany,"UD Mustofa");
array_push($arrCompany,"UD Wulandari (Persero) Tbk");
array_push($arrCompany,"UD Wahyuni Suryono Tbk");
array_push($arrCompany,"PD Handayani Andriani");
array_push($arrCompany,"PT Siregar Maulana (Persero) Tbk");
array_push($arrCompany,"PD Haryanti");
array_push($arrCompany,"UD Puspita");
array_push($arrCompany,"CV Hariyah Nainggolan");
array_push($arrCompany,"PD Ardianto Tbk");
array_push($arrCompany,"PD Agustina");
array_push($arrCompany,"Perum Melani");
array_push($arrCompany,"PD Sudiati (Persero) Tbk");
array_push($arrCompany,"UD Simbolon Santoso Tbk");
array_push($arrCompany,"PD Rajasa (Persero) Tbk");
array_push($arrCompany,"PD Habibi Halim (Persero) Tbk");
array_push($arrCompany,"PT Suryatmi (Persero) Tbk");
array_push($arrCompany,"CV Tamba Tbk");
array_push($arrCompany,"CV Rajata Tbk");
array_push($arrCompany,"PD Marbun Megantara Tbk");
array_push($arrCompany,"Perum Waluyo");
array_push($arrCompany,"CV Sitorus Mahendra Tbk");
array_push($arrCompany,"Perum Tampubolon Irawan (Persero) Tbk");
array_push($arrCompany,"PD Hidayanto Yolanda Tbk");
array_push($arrCompany,"UD Maryati Purwanti");
array_push($arrCompany,"PD Napitupulu Hardiansyah Tbk");
array_push($arrCompany,"CV Nasyiah Tbk");
array_push($arrCompany,"Perum Mandasari");
array_push($arrCompany,"PT Mayasari Maryadi");
array_push($arrCompany,"CV Wastuti Tbk");
array_push($arrCompany,"CV Simbolon Hidayat (Persero) Tbk");
array_push($arrCompany,"Perum Widiastuti Budiyanto (Persero) Tbk");
array_push($arrCompany,"CV Simanjuntak");
array_push($arrCompany,"PT Hardiansyah Waluyo");
array_push($arrCompany,"UD Rajata (Persero) Tbk");
array_push($arrCompany,"PT Latupono Yolanda");
array_push($arrCompany,"PT Agustina Rahimah (Persero) Tbk");
array_push($arrCompany,"PD Yolanda Namaga Tbk");
array_push($arrCompany,"PD Hariyah");
array_push($arrCompany,"CV Pertiwi (Persero) Tbk");
array_push($arrCompany,"UD Wasita Uyainah (Persero) Tbk");
array_push($arrCompany,"CV Hidayanto Wijayanti");
array_push($arrCompany,"PD Budiyanto Waluyo");
array_push($arrCompany,"Perum Lestari Novitasari (Persero) Tbk");
array_push($arrCompany,"CV Padmasari (Persero) Tbk");
array_push($arrCompany,"CV Saragih");
array_push($arrCompany,"UD Budiman Sihombing (Persero) Tbk");
array_push($arrCompany,"PD Susanti");
array_push($arrCompany,"PD Maulana Pudjiastuti");
array_push($arrCompany,"PT Sihombing Haryanti (Persero) Tbk");
array_push($arrCompany,"PT Prasetyo");
array_push($arrCompany,"PT Yolanda");
array_push($arrCompany,"UD Wahyuni");
array_push($arrCompany,"PT Setiawan Sihombing");
array_push($arrCompany,"PD Pudjiastuti Samosir");
array_push($arrCompany,"CV Wijaya");
array_push($arrCompany,"CV Wibisono Salahudin Tbk");
array_push($arrCompany,"PD Padmasari Tbk");
array_push($arrCompany,"CV Wacana Fujiati (Persero) Tbk");
array_push($arrCompany,"UD Lestari");
array_push($arrCompany,"CV Wibisono");
array_push($arrCompany,"PD Pradipta Wasita");
array_push($arrCompany,"Perum Maryati Haryanti");
array_push($arrCompany,"PD Wahyuni");
array_push($arrCompany,"CV Widodo Wahyudin (Persero) Tbk");
array_push($arrCompany,"Perum Prayoga Winarno Tbk");
array_push($arrCompany,"PD Wacana Uyainah");
array_push($arrCompany,"Perum Ramadan Tbk");
array_push($arrCompany,"PD Maheswara Suryono");
array_push($arrCompany,"Perum Oktaviani Tbk");
array_push($arrCompany,"UD Natsir Zulkarnain (Persero) Tbk");
array_push($arrCompany,"CV Sitorus Simanjuntak");
array_push($arrCompany,"Perum Anggraini Hartati");
array_push($arrCompany,"PT Wastuti Tampubolon");
array_push($arrCompany,"Perum Prabowo Tbk");
array_push($arrCompany,"UD Kuswandari Saputra (Persero) Tbk");
array_push($arrCompany,"UD Usamah Yuniar");
array_push($arrCompany,"Perum Januar Wastuti");
array_push($arrCompany,"PD Hidayat Tbk");
array_push($arrCompany,"PT Lestari Anggriawan (Persero) Tbk");
array_push($arrCompany,"PD Firgantoro Tbk");
array_push($arrCompany,"PD Wastuti");
array_push($arrCompany,"Perum Rahmawati");
array_push($arrCompany,"UD Jailani Tbk");
array_push($arrCompany,"UD Salahudin");
array_push($arrCompany,"Perum Sinaga Gunawan");
array_push($arrCompany,"CV Hassanah (Persero) Tbk");
array_push($arrCompany,"CV Agustina Ramadan");
array_push($arrCompany,"PT Wahyuni Laksmiwati Tbk");
array_push($arrCompany,"CV Pertiwi Tampubolon (Persero) Tbk");
array_push($arrCompany,"PT Suartini");
array_push($arrCompany,"PT Hakim Kuswoyo");
array_push($arrCompany,"PT Prasetya Wibowo Tbk");
array_push($arrCompany,"PT Hasanah Wijayanti");
array_push($arrCompany,"UD Adriansyah Rahimah (Persero) Tbk");
array_push($arrCompany,"CV Kurniawan (Persero) Tbk");
array_push($arrCompany,"UD Permata");
array_push($arrCompany,"PT Megantara");
array_push($arrCompany,"PT Sinaga Salahudin Tbk");
array_push($arrCompany,"PD Nashiruddin Uyainah");
array_push($arrCompany,"CV Wibowo");
array_push($arrCompany,"CV Winarno (Persero) Tbk");
array_push($arrCompany,"UD Mandasari Yuliarti");
array_push($arrCompany,"PT Mulyani");
array_push($arrCompany,"PT Halim (Persero) Tbk");
array_push($arrCompany,"CV Rahmawati Tbk");
array_push($arrCompany,"CV Andriani");
array_push($arrCompany,"PT Sudiati Gunawan");
array_push($arrCompany,"CV Palastri Palastri");
array_push($arrCompany,"CV Halimah Laksita (Persero) Tbk");
array_push($arrCompany,"CV Sudiati Habibi Tbk");
array_push($arrCompany,"UD Yolanda Manullang (Persero) Tbk");
array_push($arrCompany,"CV Saefullah");
array_push($arrCompany,"CV Susanti Mahendra (Persero) Tbk");
array_push($arrCompany,"Perum Widiastuti Anggraini");
array_push($arrCompany,"UD Yolanda");
array_push($arrCompany,"PT Prastuti (Persero) Tbk");
array_push($arrCompany,"Perum Rahimah Megantara (Persero) Tbk");
array_push($arrCompany,"UD Rahayu Wahyudin");
array_push($arrCompany,"PT Ardianto Kuswandari");
array_push($arrCompany,"CV Wahyuni (Persero) Tbk");
array_push($arrCompany,"PT Hasanah Mangunsong (Persero) Tbk");
array_push($arrCompany,"UD Sitompul Mardhiyah (Persero) Tbk");
array_push($arrCompany,"UD Rahimah (Persero) Tbk");
array_push($arrCompany,"PD Astuti Pertiwi Tbk");
array_push($arrCompany,"PT Anggraini Budiman");
array_push($arrCompany,"UD Riyanti Handayani Tbk");
array_push($arrCompany,"CV Putra Utama");
array_push($arrCompany,"CV Prakasa");
array_push($arrCompany,"PT Nainggolan Maryadi (Persero) Tbk");
array_push($arrCompany,"Perum Halimah Winarsih Tbk");
array_push($arrCompany,"CV Zulkarnain (Persero) Tbk");
array_push($arrCompany,"Perum Hutasoit Wibowo");
array_push($arrCompany,"UD Sudiati Prakasa");
array_push($arrCompany,"PD Palastri Hartati");
array_push($arrCompany,"Perum Nurdiyanti Agustina Tbk");
array_push($arrCompany,"PT Aryani");
array_push($arrCompany,"Perum Purwanti Waskita");
array_push($arrCompany,"PD Suryatmi Sihombing");
array_push($arrCompany,"UD Utami");
array_push($arrCompany,"CV Susanti Tbk");
array_push($arrCompany,"Perum Lailasari Widiastuti (Persero) Tbk");
array_push($arrCompany,"UD Andriani Saputra");
array_push($arrCompany,"PT Irawan");
array_push($arrCompany,"CV Aryani");
array_push($arrCompany,"UD Ardianto (Persero) Tbk");
array_push($arrCompany,"Perum Mardhiyah");
array_push($arrCompany,"PD Rahayu (Persero) Tbk");
array_push($arrCompany,"Perum Mardhiyah Hutagalung Tbk");
array_push($arrCompany,"PT Hutasoit Simanjuntak");
array_push($arrCompany,"UD Melani");
array_push($arrCompany,"Perum Latupono Halim Tbk");
array_push($arrCompany,"PT Anggraini Tbk");
array_push($arrCompany,"PT Hartati");
array_push($arrCompany,"Perum Agustina");
array_push($arrCompany,"Perum Adriansyah Laksmiwati Tbk");
array_push($arrCompany,"UD Hassanah Lestari");
array_push($arrCompany,"PT Prakasa");
array_push($arrCompany,"PT Hidayanto Damanik (Persero) Tbk");
array_push($arrCompany,"CV Susanti Siregar");
array_push($arrCompany,"UD Saefullah Purnawati (Persero) Tbk");
array_push($arrCompany,"PD Pradipta Tbk");
array_push($arrCompany,"UD Nainggolan Lestari");
array_push($arrCompany,"PT Pertiwi (Persero) Tbk");
array_push($arrCompany,"PT Sitompul Agustina Tbk");
array_push($arrCompany,"UD Pertiwi");
array_push($arrCompany,"CV Pratiwi Namaga Tbk");
array_push($arrCompany,"PD Wastuti Tbk");
array_push($arrCompany,"Perum Aryani Pranowo");
array_push($arrCompany,"CV Widiastuti Waskita");
array_push($arrCompany,"PD Farida Widiastuti Tbk");
array_push($arrCompany,"PT Mayasari Pangestu (Persero) Tbk");
array_push($arrCompany,"PD Hutapea Tbk");
array_push($arrCompany,"Perum Mandala Santoso Tbk");
array_push($arrCompany,"CV Purnawati Mahendra Tbk");
array_push($arrCompany,"CV Hutagalung Hasanah");
array_push($arrCompany,"PT Winarno (Persero) Tbk");
array_push($arrCompany,"PT Mulyani Hariyah");
array_push($arrCompany,"PT Wasita (Persero) Tbk");
array_push($arrCompany,"PD Permadi Rahayu");
array_push($arrCompany,"Perum Budiyanto (Persero) Tbk");
array_push($arrCompany,"PD Hariyah");
array_push($arrCompany,"Perum Pratiwi");
array_push($arrCompany,"CV Astuti Gunarto");
array_push($arrCompany,"CV Pradana Sinaga");
array_push($arrCompany,"UD Yolanda");
array_push($arrCompany,"PD Nugroho Tbk");
array_push($arrCompany,"PD Pangestu Wastuti");
array_push($arrCompany,"PT Mustofa Tbk");
array_push($arrCompany,"CV Hassanah");
array_push($arrCompany,"CV Wijaya (Persero) Tbk");
array_push($arrCompany,"PD Pratama");
array_push($arrCompany,"PD Purwanti Jailani Tbk");
array_push($arrCompany,"UD Lazuardi");
array_push($arrCompany,"UD Susanti");
array_push($arrCompany,"PD Rahimah (Persero) Tbk");
array_push($arrCompany,"UD Lestari Farida");
array_push($arrCompany,"CV Damanik Jailani Tbk");
array_push($arrCompany,"CV Suryono Tbk");
array_push($arrCompany,"Perum Marbun");
array_push($arrCompany,"PT Anggraini Siregar Tbk");
array_push($arrCompany,"UD Hastuti Pertiwi Tbk");
array_push($arrCompany,"CV Mayasari Pratama");
array_push($arrCompany,"Perum Winarno");
array_push($arrCompany,"PT Yulianti Tbk");
array_push($arrCompany,"PT Hastuti");
array_push($arrCompany,"UD Nugroho (Persero) Tbk");
array_push($arrCompany,"PT Firgantoro");
array_push($arrCompany,"CV Anggraini Hartati");
array_push($arrCompany,"UD Siregar Lailasari");
array_push($arrCompany,"Perum Prastuti");
array_push($arrCompany,"PD Usamah");
array_push($arrCompany,"CV Andriani Pranowo");
array_push($arrCompany,"PD Kusumo Budiyanto");
array_push($arrCompany,"PD Hidayanto Rahimah");
array_push($arrCompany,"UD Utami Anggriawan Tbk");
array_push($arrCompany,"UD Hutagalung Tbk");
array_push($arrCompany,"PD Latupono Marbun");
array_push($arrCompany,"PD Hariyah");
array_push($arrCompany,"CV Firmansyah Susanti");
array_push($arrCompany,"Perum Yuliarti Palastri (Persero) Tbk");
array_push($arrCompany,"PD Yuniar Januar (Persero) Tbk");
array_push($arrCompany,"Perum Laksita");
array_push($arrCompany,"Perum Handayani");
array_push($arrCompany,"PD Haryanti (Persero) Tbk");
array_push($arrCompany,"Perum Nasyiah Tbk");
array_push($arrCompany,"UD Yulianti (Persero) Tbk");
array_push($arrCompany,"Perum Zulkarnain Tbk");
array_push($arrCompany,"PT Nuraini Waluyo (Persero) Tbk");
array_push($arrCompany,"UD Prayoga");
array_push($arrCompany,"UD Habibi Rahimah (Persero) Tbk");
array_push($arrCompany,"UD Mulyani");
array_push($arrCompany,"UD Suryatmi (Persero) Tbk");
array_push($arrCompany,"CV Gunawan Fujiati Tbk");
array_push($arrCompany,"Perum Utami (Persero) Tbk");
array_push($arrCompany,"Perum Nasyidah Samosir Tbk");
array_push($arrCompany,"Perum Halimah");
array_push($arrCompany,"CV Napitupulu");
array_push($arrCompany,"PT Andriani");
array_push($arrCompany,"Perum Mardhiyah (Persero) Tbk");
array_push($arrCompany,"Perum Waluyo");
array_push($arrCompany,"CV Rahayu (Persero) Tbk");
array_push($arrCompany,"PD Farida Saragih (Persero) Tbk");
array_push($arrCompany,"PD Saptono Tbk");
array_push($arrCompany,"PD Suryatmi Sihotang");
array_push($arrCompany,"PD Gunarto");
array_push($arrCompany,"Perum Prasasta");
array_push($arrCompany,"Perum Budiyanto Prastuti (Persero) Tbk");
array_push($arrCompany,"PT Saptono (Persero) Tbk");
array_push($arrCompany,"CV Iswahyudi Tbk");
array_push($arrCompany,"PT Pangestu Susanti Tbk");
array_push($arrCompany,"UD Novitasari");
array_push($arrCompany,"CV Prasetya Susanti");
array_push($arrCompany,"CV Halimah");
array_push($arrCompany,"CV Pertiwi Wijayanti (Persero) Tbk");
array_push($arrCompany,"Perum Prabowo Tbk");
array_push($arrCompany,"UD Januar Hutagalung");
array_push($arrCompany,"UD Purnawati Anggraini (Persero) Tbk");
array_push($arrCompany,"CV Astuti");
array_push($arrCompany,"PT Pratiwi (Persero) Tbk");
array_push($arrCompany,"UD Nuraini Winarsih");
array_push($arrCompany,"UD Handayani Tbk");
array_push($arrCompany,"UD Wahyudin Yolanda Tbk");
array_push($arrCompany,"PD Mardhiyah");
array_push($arrCompany,"Perum Nugroho Maryati (Persero) Tbk");
array_push($arrCompany,"CV Puspita Laksita Tbk");
array_push($arrCompany,"PT Sihotang");
array_push($arrCompany,"UD Hartati Nashiruddin");
array_push($arrCompany,"PD Kuswandari (Persero) Tbk");
array_push($arrCompany,"CV Natsir Tbk");
array_push($arrCompany,"UD Wibowo Hariyah (Persero) Tbk");
array_push($arrCompany,"Perum Oktaviani Budiyanto Tbk");
array_push($arrCompany,"PD Prakasa Tbk");
array_push($arrCompany,"Perum Mahendra");
array_push($arrCompany,"PT Lestari");
array_push($arrCompany,"PT Wijayanti (Persero) Tbk");
array_push($arrCompany,"PT Tampubolon");
array_push($arrCompany,"CV Uyainah Handayani");
array_push($arrCompany,"CV Yolanda");
array_push($arrCompany,"PT Aryani (Persero) Tbk");
array_push($arrCompany,"UD Namaga Oktaviani");
array_push($arrCompany,"PT Hastuti");
array_push($arrCompany,"Perum Megantara Tbk");
array_push($arrCompany,"Perum Situmorang");
array_push($arrCompany,"PD Firmansyah Tbk");
array_push($arrCompany,"Perum Namaga");
array_push($arrCompany,"PT Puspita Tbk");
array_push($arrCompany,"PT Prasetya Waluyo");
array_push($arrCompany,"UD Marbun (Persero) Tbk");
array_push($arrCompany,"Perum Nasyiah Tbk");
array_push($arrCompany,"PT Pudjiastuti");
array_push($arrCompany,"Perum Mangunsong Kusmawati (Persero) Tbk");
array_push($arrCompany,"PT Natsir (Persero) Tbk");
array_push($arrCompany,"Perum Haryanti Santoso Tbk");
array_push($arrCompany,"UD Namaga");
array_push($arrCompany,"PT Narpati");
array_push($arrCompany,"Perum Ramadan");
array_push($arrCompany,"PD Kuswandari Agustina");
array_push($arrCompany,"Perum Puspita");
array_push($arrCompany,"PD Suryatmi Pratama");
array_push($arrCompany,"PD Usada Tbk");
array_push($arrCompany,"Perum Mandasari");
array_push($arrCompany,"PD Maryati Anggriawan (Persero) Tbk");
array_push($arrCompany,"PD Aryani");
array_push($arrCompany,"PT Mandasari (Persero) Tbk");
array_push($arrCompany,"PT Winarsih Najmudin Tbk");
array_push($arrCompany,"UD Riyanti Tampubolon");
array_push($arrCompany,"CV Prabowo Susanti");
array_push($arrCompany,"PD Mangunsong Tbk");
array_push($arrCompany,"PD Maheswara");
array_push($arrCompany,"PT Januar Pudjiastuti (Persero) Tbk");
array_push($arrCompany,"CV Waluyo Purwanti Tbk");
array_push($arrCompany,"CV Napitupulu");
array_push($arrCompany,"Perum Andriani (Persero) Tbk");
array_push($arrCompany,"PT Hidayanto Hartati Tbk");
array_push($arrCompany,"CV Laksita Hastuti");
array_push($arrCompany,"UD Widiastuti (Persero) Tbk");
array_push($arrCompany,"UD Budiman");
array_push($arrCompany,"PD Setiawan Wasita");
array_push($arrCompany,"PT Wibowo (Persero) Tbk");
array_push($arrCompany,"UD Widiastuti Salahudin (Persero) Tbk");
array_push($arrCompany,"PD Simbolon");
array_push($arrCompany,"PD Pratiwi Saputra");
array_push($arrCompany,"UD Suartini Mandasari");
array_push($arrCompany,"UD Suryatmi Tbk");
array_push($arrCompany,"PT Natsir Hariyah Tbk");
array_push($arrCompany,"CV Hutagalung Pradipta (Persero) Tbk");
array_push($arrCompany,"Perum Pangestu Pradana (Persero) Tbk");
array_push($arrCompany,"UD Maulana Yuliarti");
array_push($arrCompany,"Perum Rahayu Sitompul");
array_push($arrCompany,"PD Mustofa Riyanti");
array_push($arrCompany,"PT Suwarno (Persero) Tbk");
array_push($arrCompany,"UD Laksmiwati");
array_push($arrCompany,"CV Sitompul Sihotang Tbk");
array_push($arrCompany,"UD Laksmiwati Tbk");
array_push($arrCompany,"PT Andriani Wastuti (Persero) Tbk");
array_push($arrCompany,"PD Sudiati Tbk");
array_push($arrCompany,"CV Yulianti Winarno Tbk");
array_push($arrCompany,"PT Hardiansyah Handayani (Persero) Tbk");
array_push($arrCompany,"PD Puspita");
array_push($arrCompany,"UD Iswahyudi");
array_push($arrCompany,"UD Prasetya Tbk");
array_push($arrCompany,"Perum Novitasari Andriani (Persero) Tbk");
array_push($arrCompany,"Perum Januar");
array_push($arrCompany,"CV Rahayu Nainggolan");
array_push($arrCompany,"PD Latupono Rahmawati Tbk");
array_push($arrCompany,"UD Gunarto (Persero) Tbk");
array_push($arrCompany,"CV Mardhiyah (Persero) Tbk");
array_push($arrCompany,"CV Zulaika");
array_push($arrCompany,"CV Ramadan Hassanah");
array_push($arrCompany,"Perum Pertiwi");
array_push($arrCompany,"PT Yuliarti");
array_push($arrCompany,"UD Lailasari");
array_push($arrCompany,"PD Hassanah");
array_push($arrCompany,"CV Sihombing Novitasari Tbk");
array_push($arrCompany,"CV Susanti Nuraini");
array_push($arrCompany,"PT Suartini Handayani Tbk");
array_push($arrCompany,"PD Hutasoit");
array_push($arrCompany,"PD Habibi Tbk");
array_push($arrCompany,"PT Usada (Persero) Tbk");
array_push($arrCompany,"PD Mandasari");
array_push($arrCompany,"CV Kuswandari Tbk");
array_push($arrCompany,"PT Suryatmi Uwais");
array_push($arrCompany,"CV Prabowo");
array_push($arrCompany,"CV Wijaya Tbk");
array_push($arrCompany,"PT Mangunsong");
array_push($arrCompany,"CV Agustina");
array_push($arrCompany,"PT Waskita Lazuardi (Persero) Tbk");
array_push($arrCompany,"UD Setiawan (Persero) Tbk");
array_push($arrCompany,"UD Yuliarti Tbk");
array_push($arrCompany,"Perum Wacana (Persero) Tbk");
array_push($arrCompany,"PT Samosir Tbk");
array_push($arrCompany,"CV Mandala Maryadi");
array_push($arrCompany,"PT Hutasoit Padmasari Tbk");
array_push($arrCompany,"PD Uyainah");
array_push($arrCompany,"CV Narpati Sirait Tbk");
array_push($arrCompany,"PD Halim Pudjiastuti");
array_push($arrCompany,"PT Dabukke");
array_push($arrCompany,"PD Usamah");
array_push($arrCompany,"PD Puspita Prakasa (Persero) Tbk");
array_push($arrCompany,"PT Pranowo (Persero) Tbk");
array_push($arrCompany,"UD Prasetyo (Persero) Tbk");
array_push($arrCompany,"PD Sirait Lestari Tbk");
array_push($arrCompany,"CV Andriani");
array_push($arrCompany,"CV Yuliarti Tampubolon Tbk");
array_push($arrCompany,"PT Januar Tbk");
array_push($arrCompany,"CV Yulianti Tbk");
array_push($arrCompany,"PT Halimah (Persero) Tbk");
array_push($arrCompany,"PT Anggriawan Mahendra Tbk");
array_push($arrCompany,"Perum Wibowo Simanjuntak Tbk");
array_push($arrCompany,"UD Pratiwi Yulianti Tbk");
array_push($arrCompany,"PT Agustina Anggriawan");
array_push($arrCompany,"PD Novitasari");
array_push($arrCompany,"CV Simanjuntak");
array_push($arrCompany,"PD Utama Pratama (Persero) Tbk");
array_push($arrCompany,"Perum Siregar");
array_push($arrCompany,"PT Puspasari Tbk");
array_push($arrCompany,"CV Nainggolan");
array_push($arrCompany,"PD Laksmiwati Hastuti Tbk");
array_push($arrCompany,"Perum Salahudin");
array_push($arrCompany,"CV Tarihoran");
array_push($arrCompany,"Perum Utama");
array_push($arrCompany,"UD Wastuti Rajasa (Persero) Tbk");
array_push($arrCompany,"PD Wastuti Wibisono");
array_push($arrCompany,"UD Zulkarnain Hidayanto Tbk");
array_push($arrCompany,"PT Usada Yolanda");
array_push($arrCompany,"PD Puspasari");
array_push($arrCompany,"PD Anggriawan Natsir");
array_push($arrCompany,"PT Namaga Siregar");
array_push($arrCompany,"PT Zulaika");
array_push($arrCompany,"Perum Nugroho");
array_push($arrCompany,"PT Novitasari (Persero) Tbk");
array_push($arrCompany,"CV Latupono Yolanda (Persero) Tbk");
array_push($arrCompany,"PD Pangestu Siregar");
array_push($arrCompany,"Perum Purnawati Yuliarti Tbk");
array_push($arrCompany,"CV Yuliarti");
array_push($arrCompany,"CV Damanik");
array_push($arrCompany,"Perum Purwanti");
array_push($arrCompany,"UD Hassanah Puspasari");
array_push($arrCompany,"UD Zulaika");
array_push($arrCompany,"PT Safitri Tbk");
array_push($arrCompany,"PD Yuliarti");
array_push($arrCompany,"Perum Latupono Prasasta Tbk");
array_push($arrCompany,"Perum Waluyo");
array_push($arrCompany,"CV Widiastuti (Persero) Tbk");
array_push($arrCompany,"PD Prasetya Pradipta (Persero) Tbk");
array_push($arrCompany,"PT Wulandari Firmansyah");
array_push($arrCompany,"CV Melani Melani (Persero) Tbk");
array_push($arrCompany,"CV Latupono (Persero) Tbk");
array_push($arrCompany,"PD Prakasa Tbk");
array_push($arrCompany,"Perum Pangestu Tbk");
array_push($arrCompany,"CV Ramadan Nuraini (Persero) Tbk");
array_push($arrCompany,"PT Pangestu");
array_push($arrCompany,"Perum Wastuti (Persero) Tbk");
array_push($arrCompany,"CV Lailasari Ardianto Tbk");
array_push($arrCompany,"PT Mandasari Riyanti");
array_push($arrCompany,"UD Widodo Hariyah");
array_push($arrCompany,"UD Pertiwi Tbk");
array_push($arrCompany,"PD Wasita");
array_push($arrCompany,"Perum Thamrin Yuniar");
array_push($arrCompany,"Perum Nurdiyanti Laksmiwati Tbk");
array_push($arrCompany,"PD Sudiati (Persero) Tbk");
array_push($arrCompany,"PT Prastuti Firgantoro");
array_push($arrCompany,"CV Palastri Laksita");
array_push($arrCompany,"PT Haryanti Tbk");
    
return $arrCompany;
}
?>